name: Isolated smoke tests

on:
  pull_request:
    paths:
      - '**'
  push:
    branches: [ main ]

jobs:
  isolated-tests:
    name: Run isolated_tests smoke suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastapi httpx

      - name: Run isolated tests
        run: pytest -q isolated_tests
